site_name: 染太郎（しみたろう）のインデックス投資雑記帳
site_description: 染太郎（しみたろう）がインデックス投資を中心に語ります。
site_url: https://github.com/dozunaru/dozunaru.github.io.git

theme:
  name: material
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/extra.css
plugins:
  - blog:
      blog_dir: .
      categories_allowed:
        - 投資
        - 節約
        - 住宅
        - 散財
        - IT
  - search:
      lang: 'ja'
#  - git-revision-date-localized:
#      locale: ja
  - rss:
      match_path: posts/.* 
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags
extra:
  social:
    - icon: material/rss
      link: feed_rss_created.xml
      name: Subscribe to our RSS Feed
  analytics:
    provider: google
    property: G-BRPGWW6T26